config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  resources :molpay_transaction_histories
  resources :email_settings
  resources :regions
  resources :sources_types
  resources :product_settings
  resources :reservations do
    member do
      get "buyer"
    end
    collection do
      post "create_lot"
      get "confirm_reservation"
    end
  end

  resources :reports do
    member do
      get "menu"
      get "summary_report"
      get "analysis_age_report"
      get "analysis_unit_report"
      get "analysis_sources_type_report"
      get "analysis_region_report"
      get "analysis_race_report"
      get "sales"
      get "monthly_sales"
      get "agency_sales"
      get "cancellation"
      get "export_summary_report_excel"
      get "export_analysis_unit_excel"
      get "export_analysis_age_race_excel"
      get "export_sources_type_excel"
      get "export_regions_excel"
      get "sales_excel"
      get "monthly_excel"
    end
  end
  
  resources :buyers
  resources :company_settings 

  resources :sales do
    member do
      post "confirm"
      post "reject"
      post "cancel"
      get "new_payment"
      post "add_payment"
    end
  end

  devise_for :admins, :controllers => { :sessions => "super_admin/sessions", :registrations => "super_admin/registrations"  } # :skip => :registrations,
  devise_for :users, :controllers => { :registrations => :registrations, :sessions => :sessions  }

  resources :users do
    collection do
      post "create_member"
    end
    member do
      patch "update_member"
      delete "suspend"
      get    "activate"
    end
  end

  resources :lots do 
    member do
      post "bulk_update"
    end
  end

  resources :product_types do 
    member do 
      post "bulk_update"
    end
  end

  resources :products do 
    collection do
      post "create_lot"
      get "published"
    end
    member do
      post "update_email_setting"
      post "update_setting"
      post "update_region"
      post "update_sources_type"
      post "update_reservation_customization"
      get "site_plans"
      get "floor_plans"
    end
    resources :site_plans
    resources :floor_plans
    resources :enquiries, only: [:create, :index, :show]
  end

  resources :phases do 
    collection do 
      post "update_product"
    end
  end

  resources :projects do
    collection do
      post "update_project"
      post "update_phase"
    end
  end

  resources :companies do
    member do
      post "update_setting"
      patch "update_profile"
    end
    collection do
      get "profile"
    end
  end

  namespace :super_admin do
    resources :admins
    resources :companies do
      member do
        post "update_setting"
      end
    end
  end

  require 'sidekiq/web'
  authenticate :admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  match 'molpay/subscribe' => "molpay#subscribe", via: [:post, :get]
  match 'molpay/create_molpay_transaction' => "molpay#create_molpay_transaction", via: [:post, :get]
  match 'molpay/return_url' => "molpay#return_url", via: [:post, :get]
  match 'molpay/molpay' => "molpay#molpay", via: [:get, :post]
  
  get 'supermin_board' => 'super_admin/dashboard#index', as: :supermin_board
  root 'dashboard#index'

end

  

app/models/sale.rb
# == Schema Information
#
# Table name: sales
#
#  id                     :integer          not null, primary key
#  project_id             :integer
#  product_id             :integer
#  lot_unit_id            :integer
#  phase_id               :integer
#  user_id                :integer
#  status_id              :integer
#  buyer_id               :integer
#  downpayment            :integer
#  downpayment_percentage :integer
#  bank_loan              :string
#  spa                    :string
#  booking_fee            :integer
#  reject_reason          :string
#  downpayment_type       :string
#  confirm_date           :datetime
#  admin_confirm_user_id  :integer
#  cash                   :string
#  government_loan        :string
#  staff_loan             :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Sale < ActiveRecord::Base
  belongs_to :buyer
  belongs_to :user
  belongs_to :product
  belongs_to :project
  belongs_to :phase
  belongs_to :lot_unit
  has_many :payments
  has_one :molpay_transaction_history

  scope :confirmed, -> { where status_id: COMPLETED }

  # status
  PENDING = 1
  COMPLETED = 2
  REJECTED = 3
  CANCELLED = 4
  PENDING_RESERVATION = 5
  CONFIRM_RESERVATION = 6


  def status
  	case status_id
    when PENDING
      "Pending"
    when BOOKED
      "Booked"
    when COMPLETED
      "completed"
    when REJECTED
      "Rejected"
    when CANCELLED
      "Cancelled"
    when PENDING_RESERVATION
      "Pending Reservation"
    when CONFIRM_RESERVATION
      "Confirm Reservation"
    end
  end

  def confirm_date_short_format
    confirm_date.strftime("%d/%m/%Y") rescue ""
  end

  def lot
    Lot.find_by(id: lot_unit_id)
  end

  def actual_price
    original_price = lot.selling_price
    if buyer.is_bumiputera? && lot.is_special_unit == false
      rate_total = original_price * bumiputera_discount / 100
      original_price -= rate_total
    else
      original_price
    end
  end

  def product_setting
    @setting ||= product.product_setting
  end

  def bumiputera_discount
    product_setting.bumiputera_discount || 7
  end


end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :authenticate_project_owner!, except: [:index, :edit, :confirm_sales, :reject_sales, :new_payment, :add_payment]
  before_action :set_sale, only: [:show, :edit, :update, :destroy, :new_payment, :add_payment]

  # GET /sales
  # GET /sales.json
  def index
    return redirect_to root_path, alert: "Sorry, you don't have the access right." if is_low_level_staff?
    if is_top_level_management?
      @agencies = []
      @agencies << current_user.company.agencies
      @agencies << current_user.company
      @agencies.flatten!
      @q = Sale.where("product_id IN(?)", current_user.company.product_ids).order("created_at DESC").ransack(params[:q])
    else
      @q = current_user.sales.ransack(params[:q])
    end
    @sales = @q.result(distinct: true).order("id ASC").page(params[:page]).per(50)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sales }
    end
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @payments =  @sale.payments
    render action: 'show', layout: false
  end

  # GET /sales/new
  def new
    # @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
    
    unless is_top_level_management?
      flash[:alert] = "Sorry, you don't have the access right."
      redirect_to sales_path
    end
  end

  # POST /sales
  # POST /sales.json
  def create
    # @sale = Sale.new(sale_params)

    # respond_to do |format|
    #   if @sale.save
    #     format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
    #     format.json { render json: @sale, status: :created }
    #   else
    #     format.html { render action: 'new' }
    #     format.json { render json: @sale.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to sales_path, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    # @sale.destroy
    # respond_to do |format|
    #   format.html { redirect_to sales_url }
    #   format.json { head :no_content }
    # end
  end

  def new_payment
    @molpay_transaction = MolpayTransactionHistory.find_by(sale_id: @sale.id)
    # render :text => @sale.id.to_json
    unless @sale.user_id == current_user.id
      flash[:alert] = "Only the agent of the sale can edit."
      redirect_to sales_path
    end
  end

  def add_payment
    if @sale.user_id == current_user.id
      if params[:payment_image]
        params[:payment_image].each do |file|
          if !file.nil?
            payment = @sale.payments.new
            payment.image = file
            payment.save
          end
        end
      end
    else
      flash[:alert] = "Only the agent of the sale can edit."
    end
    redirect_to sales_path
  end

  def confirm
    if is_top_level_management?
      @sale = Sale.find params[:id]
      SaleEngine.new(@sale, sale_params).confirm
      #@sale.confirm_sale(confirm_sale_params)
      redirect_to sales_path, notice: "Sale has been confirmed."
    else
      flash[:alert] = "Sorry, you don't have the access right."
      redirect_to sales_path
    end
  end


  def reject
    sale = Sale.find(params[:id])
    if is_top_level_management? || sale.user_id == current_user.id
      SaleEngine.new(sale, reject_reason_params).reject
      redirect_to sales_path, notice: "Sale has been rejected successfully."
    else
      flash[:alert] = "Sorry, you don't have the access right."
      redirect_to sales_path
    end
  end

  def cancel
    sale = Sale.find(params[:id])
    if is_top_level_management? || sale.user_id == current_user.id
      if sale.status_id == Sale::COMPLETED
        SaleEngine.new(sale, cancel_reason_params).cancel
        flash[:notice] = "Sale has been cancelled successfully."
      else
        flash[:alert] = "The sale cannot be cancel due to invalid status."
      end
      redirect_to sales_path
    else
      flash[:alert] = "Sorry, you don't have the access right."
      redirect_to sales_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:admin_confirm_user_id ,:user_id, :downpayment, :downpayment_percentage ,:downpayment_type, :cash, :bank_loan, :government_loan, :staff_loan , :spa, :confirm_date, :purchaser_name, :purchaser_address, :purchaser_ic_number, :purchaser_contact_number)
    end

    def reject_reason_params
      params.require(:sale).permit(:reject_reason)
    end

    def cancel_reason_params
      params.require(:sale).permit(:cancel_reason)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_cancel_sale_form.html.erb
<%= form_tag cancel_sale_path(sale), {:class => 'panel-body form-horizontal form-padding'}  do %>

  <%# if @customization.reject_reason? %>
    <div class="form-group">
      <label class="col-md-3 control-label" for="sale_cancel_reason">Cancel Reason:</label>
      <div class="col-md-9">
        <input type="text" id="sale_cancel_reason" name="sale[cancel_reason]" class="form-control" placeholder="Cancel Reason" <%#= @customization.reject_reason_required? ? 'required' : nil %> >
          <%# if @customization.reject_reason_required? %>
            <!-- <small class="help-block">Required field</small> -->
          <%# end %>
      </div>
    </div>
  <%# else %>
    <!-- Unable keyin cancel reason. -->
  <%# end %>
  <div class="form-group">
    <div class="row">
      <div class="col-sm-9 col-sm-offset-3">
        <br>
        <button class="btn btn-info btn-labeled fa fa-user fa-lg" type="submit">Submit</button>
        <!-- <button class="btn btn-warning btn-labeled fa fa-repeat fa-lg" type="reset" id="back_btn">Back</button> -->
      </div>
    </div>
  </div>

<% end %>

app/views/sales/_confirm_sale_form.html.erb
<%= form_tag confirm_sale_path(sale), {:class => 'panel-body form-horizontal form-padding'}  do %>

  <% if is_top_level_management? %>

  <% product = Product.find(sale.product_id) %>
  <% @customization = product.reservation_customization %>

  <% if @customization.sale_person %>
    <div class="form-group">
      <label class="col-md-3 control-label" for="sale_user_id">Sale Person</label>
      <div class="col-md-9">
        <select class="selectpicker" name="sale[user_id]" <%= @customization.sale_person_required? ? 'required' : nil %> >
          <option value="">Select a name</option>
          <% current_user.company.members.each do |member| %>
            <option value="<%= member.id %>" <%= member.id == sale.user_id ? "selected='selected'" : nil %> ><%= member.name %></option>
          <% end %>
        </select>
        <% if @customization.sale_person_required?  %>
          <small class="help-block">Required field</small>
        <% end %>
      </div>
    </div>
  <% end %>


  <input type="hidden" name="sale[admin_confirm_user_id]" class="form-control" value="<%= current_user.id %>">
    <br>
  
  <% if @customization.confirm_date? %>
    <div class="form-group">
      <label class="col-md-3 control-label" for="sale_confirm_date">SPA Date</label>
      <div class="col-md-9">
        <div class="input-group date">
          <input type="text" class="form-control" name="sale[confirm_date]" id="sale_confirm_date" value="" <%= @customization.confirm_date_required? ? 'required' : nil %> >
          <span class="input-group-addon"><i class="fa fa-calendar fa-lg"></i></span>
        </div>
        
        <small class="text-muted">Click to select the SPA date. </small>
        <% if @customization.confirm_date_required?  %>
          <small class="help-block">Required field</small>
        <% end %>
      </div>
    </div>
    <% end %>
    <br>


  <% if @customization.downpayment? %>
  <div class="form-group">
    <label class="col-md-3 control-label" for="sale_downpayment">Down Payment(RM):</label>
    <div class="col-md-9">
      <input type="text" id="sale_downpayment" name="sale[downpayment]" class="form-control" placeholder="DownPayment" value="" <%= @customization.downpayment_required? ? 'required' : nil %> >
      <% if @customization.downpayment_required?  %>
          <small class="help-block">Required field</small>
        <% end %>
    </div>
  </div>
  <% end %>
  <br>

  <% if @customization.downpayment_percentage? %>
  <div class="form-group">
    <label class="col-md-3 control-label" for="sale_downpayment_percentage">Down Payment(%): </label>
    <div class="col-md-9">
      <input type="text" id="sale_downpayment_percentage" name="sale[downpayment_percentage]" class="form-control" placeholder="Downpayment percentage" value="" <%= @customization.downpayment_percentage_required? ? 'required' : nil %> >
      <% if @customization.downpayment_percentage_required?  %>
        <small class="help-block">Required field</small>
      <% end %>
    </div>
  </div>
  <% end %>
  <br>

  <% if @customization.downpayment_type? %>
  <div class="form-group">
    <label class="col-md-3 control-label" for="sale_downpayment_type">Downpayment Type: </label>
    <div class="col-md-9">
      <input type="text" id="sale_downpayment_type" name="sale[downpayment_type]" class="form-control" placeholder="Downpayment Type" value="" <%= @customization.downpayment_type_required? ? 'required' : nil %> >
      <% if @customization.downpayment_type_required?  %>
        <small class="help-block">Required field</small>
      <% end %>
    </div>
  </div>
  <% end %>
  <br>
  <% if @customization.payment_type? %>
  <div class="form-group">
    <label class="col-md-3 control-label" for="sale_payment_type">Payment Type: </label>
    <div class="col-md-9">
      <input type="text" id="sale_bank_loan" name="sale[payment_type]" class="form-control" placeholder="Payment Type" value="" <%= @customization.payment_type_required? ? 'required' : nil %> >
      <% if @customization.payment_type_required?  %>
        <small class="help-block">Required field</small>
      <% end %>
    </div>
  </div>
  <% end %>
  <br>

  <% if @customization.spa? %>
  <div class="form-group">
    <label class="col-md-3 control-label" for="sale_spa">SPA/Solicitor: </label>
    <div class="col-md-9">
      <input type="text" id="sale_spa" name="sale[spa]" class="form-control" placeholder="SPA Lawyer Firm" value="" <%= @customization.spa_required? ? 'required' : nil %> >
      <% if @customization.spa_required?  %>
        <small class="help-block">Required field</small>
      <% end %>
    </div>
  </div>
  <% end %>
  <br>

  <% if @customization.cash? %>
  <div class="form-group">
    <label class="col-md-3 control-label" for="sale_cash">Cash: </label>
    <div class="col-md-9">
      <input type="text" id="sale_cash" name="sale[cash]" class="form-control" placeholder="Cash" value="<%= sale.cash? ? sale.cash : nil %>" <%= @customization.cash_required? ? 'required' : nil %> >
      <% if @customization.cash_required?  %>
        <small class="help-block">Required field</small>
      <% end %>
    </div>
  </div>
  <% end %>
  <br>

  <% if @customization.bank_loan? %>
  <div class="form-group">
    <label class="col-md-3 control-label" for="sale_bank_loan">Bank Loan: </label>
    <div class="col-md-9">
      <input type="text" id="sale_bank_loan" name="sale[bank_loan]" class="form-control" placeholder="Bank Loan" value="<%= sale.bank_loan ? sale.bank_loan : nil %>" <%= @customization.cash_required? ? 'required' : nil %> >
      <% if @customization.bank_loan_required?  %>
        <small class="help-block">Required field</small>
      <% end %>
    </div>
  </div>
  <% end %>
  <br>

  <% if @customization.government_loan? %>
  <div class="form-group">
    <label class="col-md-3 control-label" for="sale_government_loan">Bank Loan: </label>
    <div class="col-md-9">
      <input type="text" id="sale_government_loan" name="sale[government_loan]" class="form-control" placeholder="Bank Loan" value="<%= sale.government_loan ? sale.government_loan : nil %>" <%= @customization.government_loan_required? ? 'required' : nil %> >
      <% if @customization.government_loan_required?  %>
        <small class="help-block">Required field</small>
      <% end %>
    </div>
  </div>
  <% end %>
  <br>

  <% if @customization.staff_loan? %>
  <div class="form-group">
    <label class="col-md-3 control-label" for="sale_staff_loan">Staff Loan: </label>
    <div class="col-md-9">
      <input type="text" id="sale_staff_loan" name="sale[staff_loan]" class="form-control" placeholder="Staff Loan" value="<%= sale.staff_loan ? sale.staff_loan : nil %>" <%= @customization.staff_loan? ? 'required' : nil %> >
      <% if @customization.staff_loan_required?  %>
        <small class="help-block">Required field</small>
      <% end %>
    </div>
  </div>
  <% end %>
  <br>

  
  <% end %>
  <div class="form-group">
    <div class="row">
      <div class="col-sm-9 col-sm-offset-3">
          <br>
        <button class="btn btn-info btn-labeled fa fa-user fa-lg" type="submit">Submit</button>
        <!-- <button class="btn btn-warning btn-labeled fa fa-repeat fa-lg" type="reset" id="back_btn">Back</button> -->
      </div>
    </div>
  </div>

<% end %>

app/views/sales/_form.html.erb
<%= form_for(@sale, html: {:class => 'panel-body form-horizontal form-padding', :multipart => true }) do |f| %>

    <div class="form-group">
      <label class="col-md-3 control-label" for="sale_user_id">Sale Person</label>
      <div class="col-md-9">
          <!-- Inline radio buttons -->
        <select class="selectpicker" name="sale[user_id]">
          <option value="">Select a name</option>
          <% current_user.company.members.each do |member| %>
            <option value="<%= member.id %>" <%= member.id == @sale.user_id ? "selected='selected'" : nil %> ><%= member.name %></option>
          <% end %>
        </select>
      </div>
    </div>
    <br>

  <div class="form-group">
      <label class="col-md-3 control-label" for="sale_user_id">SPA Date</label>
      <div class="col-md-9">
      <div class="input-group date">
        <input type="text" class="form-control" name="sale[confirm_date]" id="sale_confirm_date" value="<%= @sale.confirm_date_short_format %>">
        <span class="input-group-addon"><i class="fa fa-calendar fa-lg"></i></span>
      </div>
      <small class="text-muted">Click to change the date</small>
    </div>
  </div>
  <br>

  <div class="form-group">
    <label class="col-md-3 control-label" for="sale_downpayment">Down Payment(RM):</label>
    <div class="col-md-9">
      <input type="number" id="sale_downpayment" name="sale[downpayment]" class="form-control" placeholder="DownPayment" value="<%= @sale.downpayment %>">
      <!-- <small class="help-block">This is a help text</small> -->
    </div>
  </div>
  <br>
  <div class="form-group">
    <label class="col-md-3 control-label" for="sale_downpayment_percentage">Down Payment(%): </label>
    <div class="col-md-9">
      <input type="number" id="sale_downpayment_percentage" name="sale[downpayment_percentage]" class="form-control" placeholder="DownPayment percentage" value="<%= @sale.downpayment_percentage %>">
    </div>
  </div>
  <br>
  <div class="form-group">
    <label class="col-md-3 control-label" for="sale_downpayment_type">Payment Type: </label>
    <div class="col-md-9">
      <input type="text" id="sale_downpayment_type" name="sale[downpayment_type]" class="form-control" placeholder="Down Payment Type" value="<%= @sale.downpayment_type %>">
    </div>
  </div>
  <br>
  <div class="form-group">
    <label class="col-md-3 control-label" for="sale_bank_loan">Bank Loan: </label>
    <div class="col-md-9">
      <input type="text" id="sale_bank_loan" name="sale[bank_loan]" class="form-control" placeholder="Bank Loan" value="<%= @sale.bank_loan %>">
    </div>
  </div>
  <br>
  <div class="form-group">
    <label class="col-md-3 control-label" for="sale_spa">Lawyer Firm: </label>
    <div class="col-md-9">
      <input type="text" id="sale_spa" name="sale[spa]" class="form-control" placeholder="SPA" value="<%= @sale.spa %>">
    </div>
  </div>

  <br>
  <div class="form-group">
    <div class="row">
      <div class="col-sm-9 col-sm-offset-3">
          <br>
        <button class="btn btn-info btn-labeled fa fa-user fa-lg" type="submit">Submit</button>
        <button class="btn btn-warning btn-labeled fa fa-repeat fa-lg" type="reset" id="back_btn">Back</button>
      </div>
    </div>
  </div>

<% end %>

app/views/sales/_reject_sale_form.html.erb
<%= form_tag reject_sale_path(sale), {:class => 'panel-body form-horizontal form-padding'}  do %>
  
  <% @product = Product.friendly.find(sale.product_id) %>
  <% @customization = @product.reservation_customization %>

  <div class="form-group">
    <label class="col-md-3 control-label" for="sale_reject_reason">Reject Reason:</label>
    <div class="col-md-9">
      <input type="text" id="sale_reject_reason" name="sale[reject_reason]" class="form-control" placeholder="Reject Reason" <%= @customization.reject_reason_required? ? 'required' : nil %>>
    <% if @customization.reject_reason_required?  %>
      <small class="help-block">Required field</small>
    <% end %>
    </div>
  </div>

  <div class="form-group">
    <div class="row">
      <div class="col-sm-9 col-sm-offset-3">
        <br>
        <button class="btn btn-info btn-labeled fa fa-user fa-lg" type="submit">Submit</button>
        <!-- <button class="btn btn-warning btn-labeled fa fa-repeat fa-lg" type="reset" id="back_btn">Back</button> -->
      </div>
    </div>
  </div>

<% end %>

app/views/sales/edit.html.erb
<% content_for :stylesheets do %>
  <link href="/plugins/bootstrap-datepicker/bootstrap-datepicker.css" rel="stylesheet">
<% end %>

<% content_for :javascripts do %>
  <script src="/plugins/bootstrap-datepicker/bootstrap-datepicker.js"></script>
  <script src="/js/demo/form-component.js"></script>
  <script type="text/javascript">
    $('#sale_confirm_date').datepicker({
      format: 'dd/mm/yyyy',
      autoclose: true
    });
  
	  $("#back_btn").click(function(e){
	    e.preventDefault();
	    window.location.href='<%= sales_path %>';
	  });

	</script>
<% end %>

<div class="row" id="content_div">
	<div class="col-lg-12">
		<div class="panel">
			<div class="panel-heading">
				<h3 class="panel-title">Editing Sale detail</h3>
			</div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/new_payment.html.erb
<% content_for :javascripts do %>
  <script type="text/javascript">
    $("#back_btn").click(function(e){
      e.preventDefault();
      window.location.href='<%= sales_path %>';
    });

  </script>
<% end %>
<div class="row" id="content_div">
  <div class="col-lg-12">
    <div class="panel">
      <div class="panel-heading">
        <h3 class="panel-title">Payment</h3>
      </div>
      <%= form_tag add_payment_sale_path(@sale), :class => 'panel-body form-horizontal form-padding', :multipart => true do  %>
       

        <% if @sale.user_id == current_user.id %>
            <br>
            <div class="form-group">
              <label class="col-md-3 control-label" for="payment_image">Cheque/Transaction Slip: </label>
              <div class="col-md-9 upload_payments_wrapper">
                <div class="upload_fields">
                  <input type="file" id="payment_image" name="payment_image[]" class="form-control" required>
                  <% 4.times do %>
                    <input type="file" id="payment_image" name="payment_image[]" class="form-control" >
                  <% end %>
                </div>
                <!-- <button class="add_more_photo_button btn btn-info">Add more photo</button> -->
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-6 control-label">
                <h4>Or</h4>
              </label>
            </div>
            <hr>

            <%# if is_top_level_admin? %>
            <div class="form-group">
              <label class="col-md-3 control-label">
                With Credit Card / Online Banking:
              </label>
              <div class="col-md-5">
                <% if @molpay_transaction && @molpay_transaction.status == MolpayTransactionHistory::SUCCESS %>
                  <%= link_to "View Molpay Transaction", molpay_transaction_history_path(@sale.id) %>
                  <!-- Molpay Successfully Paid -->
                <% else %>
                  <%= link_to "Pay Now", molpay_subscribe_path(:id => @sale.id), :class=>"btn btn-warning" %>
                <% end %>
              </div>
              <div class="col-md-4">
                <img class="img-responsive" src="/img/slack-imgs.com.jpeg" alt="Image">
              </div>
            </div>
            <%# end %>
        <% end %>

        <br>
        <div class="form-group">
          <div class="row">
            <div class="col-sm-9 col-sm-offset-3">
                <br>
              <button class="btn btn-info btn-labeled fa fa-user fa-lg" type="submit">Submit</button>
              <button class="btn btn-warning btn-labeled fa fa-repeat fa-lg" type="reset" id="back_btn">Back</button>
            </div>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/sales/show.html.erb
<div id="payment-carousel" class="carousel slide" data-ride="carousel">
          
  <!--Indicators-->
  <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
  <ol class="carousel-indicators dark out">
    <% @payments.each_with_index do |payment, index| %>
    <li class="<%= index == 0 ? 'active' : nil %>" data-slide-to="<%= index  %>" data-target="#payment-carousel"></li>
    <% end %>
   <!--  <li data-slide-to="1" data-target="#payment-carousel"></li>
    <li class="" data-slide-to="2" data-target="#payment-carousel"></li> -->
  </ol>
  <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

  <div class="carousel-inner text-center">
    <% @payments.each_with_index do |payment, index| %>
      <div class="item <%= index == 0 ? 'active' : nil %>">
        <div class="media text-center"><img src="<%= payment.image.url %>" alt="Payment image"></div>
      </div>
    <% end %>
  </div>

  <!--carousel-control-->
  <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
  <a class="carousel-control left" data-slide="prev" href="#payment-carousel"><i class="fa fa-chevron-left fa-2x"></i></a>
  <a class="carousel-control right" data-slide="next" href="#payment-carousel"><i class="fa fa-chevron-right fa-2x"></i></a>
  <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

</div>
<!--===================================================-->
<!--End Carousel-->